# Generated by Django 3.1.2 on 2020-12-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='place_fk',
        ),
        migrations.AlterField(
            model_name='provider',
            name='place_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
