# Generated by Django 3.1.2 on 2020-12-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201201_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='place_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.place'),
        ),
    ]
