# Generated by Django 3.1.2 on 2020-12-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201207_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='place_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.place'),
        ),
    ]
